-- phpMyAdmin SQL Dump
-- version 5.0.2
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Generation Time: Oct 24, 2020 at 05:07 PM
-- Server version: 5.7.31-0ubuntu0.18.04.1
-- PHP Version: 7.2.34-4+ubuntu18.04.1+deb.sury.org+1

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `cms`
--

-- --------------------------------------------------------

--
-- Table structure for table `categories`
--

CREATE TABLE `categories` (
  `cat_id` int(3) NOT NULL,
  `cat_title` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `categories`
--

INSERT INTO `categories` (`cat_id`, `cat_title`) VALUES
(1, 'Bootstrap'),
(2, 'JavaScript'),
(17, 'Php'),
(21, 'Java'),
(22, 'Random category');

-- --------------------------------------------------------

--
-- Table structure for table `posts`
--

CREATE TABLE `posts` (
  `post_id` int(3) NOT NULL,
  `post_category_id` int(3) NOT NULL,
  `post_title` varchar(255) NOT NULL,
  `post_author` varchar(255) NOT NULL,
  `post_date` date NOT NULL,
  `post_image` text NOT NULL,
  `post_content` text NOT NULL,
  `post_tags` varchar(255) NOT NULL,
  `post_comment_count` int(5) NOT NULL,
  `post_status` varchar(255) NOT NULL DEFAULT 'draft'
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `posts`
--

INSERT INTO `posts` (`post_id`, `post_category_id`, `post_title`, `post_author`, `post_date`, `post_image`, `post_content`, `post_tags`, `post_comment_count`, `post_status`) VALUES
(1, 1, 'Acika\'s post', 'acika', '2020-10-06', 'image_1.jpg', 'sdfgasdfasdfasdfaf asdfasdfadsf', 'acika, bootstrap', 0, 'draft'),
(45, 1, 'asdfsd', 'asdfsadf', '2020-10-12', 'image_3.jpg', '         asdf                                                                                 ', 'asdf', 4, 'asf'),
(46, 1, '1234qweeew', 'qwerq', '2020-10-12', 'image_2.jpg', '         qwer                  ', 'qwer', 4, 'qrrew'),
(47, 2, 'Jednacina', 'Aleks', '2020-10-24', '', '         <math display=\"block\" xmlns=\"http://www.w3.org/1998/Math/MathML\">\r\n<!-- Generated By: JMathEdit2.2.4-->\r\n<!-- Pilot Software, Ltd-->\r\n<!-- http://www.pilotltd.com-->\r\n<mstyle scriptlevel=\"0\" displaystyle=\"true\">\r\n<mrow>\r\n<mstyle  mathcolor=\"#333333\">\r\n<mover>\r\n<mrow>\r\n<msubsup>\r\n<mrow>\r\n<mi>C</mi>\r\n</mrow>\r\n<mrow>\r\n<mi>9</mi>\r\n</mrow>\r\n<mrow>\r\n<mn>6</mn>\r\n</mrow>\r\n</msubsup>\r\n</mrow>\r\n<mo stretchy=\"true\">&OverBar;</mo>\r\n</mover>\r\n</mstyle>\r\n<mo>=</mo>\r\n<mstyle  mathcolor=\"#333333\">\r\n<mfrac>\r\n<mrow>\r\n<mi>9!</mi>\r\n</mrow>\r\n\r\n<mrow>\r\n<mo>(</mo>\r\n<mi>9</mi>\r\n<mo>&#8722;</mo>\r\n<mn>6</mn>\r\n<mo>)</mo>\r\n<mi>!*</mi>\r\n<mn>6</mn>\r\n<mi>!</mi>\r\n</mrow>\r\n\r\n</mfrac>\r\n</mstyle>\r\n<mo>=</mo>\r\n<mstyle  mathcolor=\"#333333\">\r\n<mfrac>\r\n<mrow>\r\n<mi>9!</mi>\r\n</mrow>\r\n\r\n<mrow>\r\n<mn>3</mn>\r\n<mi>!*</mi>\r\n<mn>6</mn>\r\n<mi>!</mi>\r\n</mrow>\r\n\r\n</mfrac>\r\n</mstyle>\r\n<mo>=</mo>\r\n<mstyle  mathcolor=\"#333333\">\r\n<mfrac>\r\n<mrow>\r\n<mi>9*</mi>\r\n<mn>7</mn>\r\n<mi>*</mi>\r\n<mn>8</mn>\r\n<mi>*</mi>\r\n<mn>6</mn>\r\n<mi>!</mi>\r\n</mrow>\r\n\r\n<mrow>\r\n<mn>3</mn>\r\n<mi>!*</mi>\r\n<mn>6</mn>\r\n<mi>!</mi>\r\n</mrow>\r\n\r\n</mfrac>\r\n</mstyle>\r\n<mo>=</mo>\r\n<mstyle  mathcolor=\"#333333\">\r\n<mfrac>\r\n<mrow>\r\n<mi>9*</mi>\r\n<mn>7</mn>\r\n<mi>*</mi>\r\n<mn>8</mn>\r\n</mrow>\r\n\r\n<mrow>\r\n<mn>3</mn>\r\n<mi>*</mi>\r\n<mn>2</mn>\r\n<mi>*</mi>\r\n<mn>1</mn>\r\n</mrow>\r\n\r\n</mfrac>\r\n</mstyle>\r\n<mo>=</mo>\r\n<mstyle  mathcolor=\"#333333\">\r\n<mfrac>\r\n<mrow>\r\n<mn>504</mn>\r\n</mrow>\r\n\r\n<mrow>\r\n<mn>6</mn>\r\n</mrow>\r\n\r\n</mfrac>\r\n</mstyle>\r\n<mo>=</mo>\r\n<mn>84</mn>\r\n</mrow>\r\n\r\n</mstyle>\r\n</math>\r\n', 'Math', 4, 'published'),
(48, 1, 'Jednacina II', 'Aleksa', '2020-10-24', '', '<math display=\"block\" xmlns=\"http://www.w3.org/1998/Math/MathML\">\r\n<!-- Generated By: JMathEdit2.2.4-->\r\n<!-- Pilot Software, Ltd-->\r\n<!-- http://www.pilotltd.com-->\r\n<mstyle scriptlevel=\"0\" displaystyle=\"true\">\r\n<mrow>\r\n<mstyle  mathcolor=\"#333333\">\r\n<msubsup>\r\n<mrow>\r\n<mover>\r\n<mrow>\r\n<mi>C</mi>\r\n</mrow>\r\n<mo accent=\"true\">Ì…</mo>\r\n</mover>\r\n</mrow>\r\n<mrow>\r\n<mi>9</mi>\r\n</mrow>\r\n<mrow>\r\n<mn>6</mn>\r\n</mrow>\r\n</msubsup>\r\n</mstyle>\r\n<mo>=</mo>\r\n<mstyle  mathcolor=\"#333333\">\r\n<mfrac>\r\n<mrow>\r\n<mi>9!</mi>\r\n</mrow>\r\n\r\n<mrow>\r\n<mo>(</mo>\r\n<mi>9</mi>\r\n<mo>âˆ’</mo>\r\n<mn>6</mn>\r\n<mo>)</mo>\r\n<mi>!</mi>\r\n<mn>6</mn>\r\n<mi>!</mi>\r\n</mrow>\r\n\r\n</mfrac>\r\n</mstyle>\r\n<mo>=</mo>\r\n<mstyle  mathcolor=\"#333333\">\r\n<mfrac>\r\n<mrow>\r\n<mi>9*</mi>\r\n<mn>8</mn>\r\n<mi>*</mi>\r\n<mn>7</mn>\r\n<mi>*</mi>\r\n<mn>6</mn>\r\n<mi>!</mi>\r\n</mrow>\r\n\r\n<mrow>\r\n<mn>3</mn>\r\n<mi>!*</mi>\r\n<mn>6</mn>\r\n<mi>!</mi>\r\n</mrow>\r\n\r\n</mfrac>\r\n</mstyle>\r\n<mo>=</mo>\r\n<mstyle  mathcolor=\"#333333\">\r\n<mfrac>\r\n<mrow>\r\n<mi>9*</mi>\r\n<mn>8</mn>\r\n<mi>*</mi>\r\n<mn>7</mn>\r\n</mrow>\r\n\r\n<mrow>\r\n<mn>3</mn>\r\n<mi>*</mi>\r\n<mn>2</mn>\r\n<mi>*</mi>\r\n<mn>1</mn>\r\n</mrow>\r\n\r\n</mfrac>\r\n</mstyle>\r\n<mo>=</mo>\r\n<mstyle  mathcolor=\"#333333\">\r\n<mfrac>\r\n<mrow>\r\n<mn>504</mn>\r\n</mrow>\r\n\r\n<mrow>\r\n<mn>6</mn>\r\n</mrow>\r\n\r\n</mfrac>\r\n</mstyle>\r\n<mo>=</mo>\r\n<mn>84</mn>\r\n</mrow>\r\n\r\n</mstyle>\r\n</math>\r\n         ', 'jednacina', 4, 'P');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `categories`
--
ALTER TABLE `categories`
  ADD PRIMARY KEY (`cat_id`);

--
-- Indexes for table `posts`
--
ALTER TABLE `posts`
  ADD PRIMARY KEY (`post_id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `categories`
--
ALTER TABLE `categories`
  MODIFY `cat_id` int(3) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=23;

--
-- AUTO_INCREMENT for table `posts`
--
ALTER TABLE `posts`
  MODIFY `post_id` int(3) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=49;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
